# -*- coding: utf-8 -*-
"""YOLO11m_with_tiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MEM9cadEOkVsKFXg11L9_O3ZbU3IXuu
"""

from ultralytics import YOLO
import os
import cv2
import random
import matplotlib.pyplot as plt

# dataset path
dataset_path = "/home/vietpham/dataset/dataset"
image_dir = os.path.join(dataset_path, "train/labels")
label_dir = os.path.join(dataset_path, "train/labels")



# Get all image files
image_files = [f for f in os.listdir(image_dir) if f.endswith((".jpg", ".png", ".jpeg"))]
print(f"Found {len(image_files)} training images.")

class_names = [
    "tlr", "tly", "tlg", "tlra", "tlya", "tlga", "tsra", "tsya", "tsga",
    "trra", "trya", "trga", "tura", "tuya", "tuga", "tln", "tlr", "tly", "tlg",
    "tlra", "tlya", "tlga", "tsra", "tsya", "tsga", "trra", "trya", "trga",
    "tura", "tuya", "tuga", "tln",
    "117", "118", "119", "120", "121", "122", "123", "124", "125", "126",
    "127", "128", "129", "130", "131", "132", "133", "134", "135", "136",
    "137", "138", "139", "140", "141",
    "tnr", "tny", "tng", "tcr", "tcg", "tcn",
    "tllv", "tllvr", "tllvy", "tllvg", "tlrv", "tlrvr", "tlrvy", "tlrvg",
    "tlbv", "tclv", "tclvr", "tclvg", "tcrv", "tcrvr", "tcrvg", "tcbv"
]

# Random sample images
image_files = [f for f in os.listdir(image_dir) if f.endswith((".jpg", ".png"))]
sample_images = random.sample(image_files, min(1, len(image_files)))

def draw_yolo_labels(image_path, label_path):
    img = cv2.imread(image_path)
    if img is None: return None
    h, w = img.shape[:2]

    with open(label_path, "r") as f:
        for line in f:
            cls, x, y, bw, bh = map(float, line.split())
            cls = int(cls)
            x1, y1 = int((x - bw / 2) * w), int((y - bh / 2) * h)
            x2, y2 = int((x + bw / 2) * w), int((y + bh / 2) * h)
            color = (0, 255, 0)
            label = class_names[cls] if cls < len(class_names) else str(cls)
            cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
            cv2.putText(img, label, (x1, y1 - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(15, 10))
for i, name in enumerate(sample_images):
    img_path = os.path.join(image_dir, name)
    label_path = os.path.join(label_dir, os.path.splitext(name)[0] + ".txt")
    img_disp = draw_yolo_labels(img_path, label_path)
    if img_disp is not None:
        plt.subplot(1, len(sample_images), i + 1)
        plt.imshow(img_disp)
        plt.axis("off")
        plt.title(name)
plt.show()

yaml_path = os.path.join(dataset_path, "data.yaml")
with open(yaml_path, "w") as f:
    f.write(f"""
path: {dataset_path}
train: train/images
val: val/images
test: test/images

names:
""")
    for i, name in enumerate(class_names):
        f.write(f"  {i}: {name}\n")

print(open(yaml_path).read())

# # Choose model size: yolov8n (nano), yolov8s (small), yolov8m (medium), yolov8l (large)
# model = YOLO('yolov8m.pt')  # start from pretrained COCO weights
# # model = YOLO('./runs/traffic_light_yolo_tiling_bosch3/weights/best.pt')

# import ultralytics
# from ultralytics import YOLO

# # ✅ Check Ultralytics version
# print("Ultralytics package version:", ultralytics.__version__)

# # ✅ Print model details to see what version/core it's using
# print("Model type:", type(model))
# print("Model info:", model.info())

# # ✅ Print model name or architecture
# try:
#     print("Model YAML path:", model.model.yaml_file)
# except Exception as e:
#     print("Could not get YAML file:", e)

# # ✅ If YOLO11, you'll usually see something like:
# # 'YOLOv11Model' or 'yolo11m' in the outputs.

# # Train model
# model.train(
#     data=yaml_path,
#     epochs=100,             # increase if you have GPU time
#     imgsz=640,             # image size (can change to 416 or 1280)
#     batch=16,
#     name='traffic_light_yolo_dataset2',
#     project='./runs',  # where to save results
#     device=0,# use GPU if available
# )

# # Evaluate on validation set
# metrics = model.val()
# print(metrics)

# # # Visualize predictions
# # results = model.predict(source=f"{dataset_path}/images/test_tiled", conf=0.25, save=True)

# # # from IPython.display import Image, display
# # # display(Image(filename="/content/drive/MyDrive/Applied ML/Lab/runs/traffic_light_yolo/results.png", width=800))

# # print(metrics.results_dict)

# # import os
# # import glob
# # import cv2
# # import math
# # import numpy as np
# # from ultralytics import YOLO
# # import matplotlib.pyplot as plt

# # # --- Load trained model ---
# # model = YOLO("/content/drive/MyDrive/Applied ML/Lab/runs/traffic_light_yolo_tiling_bosch/weights/best.pt")

# # # --- Define dataset paths ---
# # val_images = sorted(glob.glob(os.path.join(dataset_path, "images/test_tiled/*.png")))

# # # --- Tiling parameters ---
# # TILE_SIZE = 640
# # OVERLAP = 0.2  # 20% overlap

# # def get_tiles(img, tile_size=TILE_SIZE, overlap=OVERLAP):
# #     h, w, _ = img.shape
# #     step = int(tile_size * (1 - overlap))
# #     tiles = []
# #     for y in range(0, h, step):
# #         for x in range(0, w, step):
# #             x2 = min(x + tile_size, w)
# #             y2 = min(y + tile_size, h)
# #             tile = img[y:y2, x:x2]
# #             tiles.append((tile, x, y))  # store top-left coords
# #     return tiles

# # def run_tiled_inference(model, img, conf=0.25):
# #     h, w, _ = img.shape
# #     combined_results = []

# #     tiles = get_tiles(img)
# #     for tile, offset_x, offset_y in tiles:
# #         results = model.predict(tile, conf=conf, verbose=False)
# #         for box in results[0].boxes:
# #             x1, y1, x2, y2 = box.xyxy[0]
# #             cls = int(box.cls[0])
# #             conf_score = float(box.conf[0])
# #             # shift coords back to full image
# #             gx1, gy1 = x1 + offset_x, y1 + offset_y
# #             gx2, gy2 = x2 + offset_x, y2 + offset_y
# #             combined_results.append((gx1, gy1, gx2, gy2, cls, conf_score))
# #     return combined_results

# # def draw_combined_predictions(img, detections, color=(0, 0, 255)):
# #     out = img.copy()
# #     for (x1, y1, x2, y2, cls, conf) in detections:
# #         cv2.rectangle(out, (int(x1), int(y1)), (int(x2), int(y2)), color, 2)
# #         cv2.putText(out, f"{cls}:{conf:.2f}", (int(x1), int(y1) - 5),
# #                     cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 1)
# #     return out

# # # --- Draw YOLO Ground Truth Boxes ---
# # def draw_yolo_boxes(image_path, label_path, color=(0, 255, 0), label_type="GT"):
# #     img = cv2.imread(image_path)
# #     h, w, _ = img.shape
# #     if os.path.exists(label_path):
# #         with open(label_path, "r") as f:
# #             for line in f.readlines():
# #                 cls, x, y, bw, bh = map(float, line.strip().split())
# #                 x1, y1 = int((x - bw / 2) * w), int((y - bh / 2) * h)
# #                 x2, y2 = int((x + bw / 2) * w), int((y + bh / 2) * h)
# #                 cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
# #                 cv2.putText(img, f"{int(cls)}-{label_type}", (x1, y1 - 4),
# #                             cv2.FONT_HERSHEY_SIMPLEX, 0.4, color, 1, cv2.LINE_AA)
# #     return img

# # # --- Run prediction on sample images ---
# # sample_images = val_images[4:7]
# # for img_path in sample_images:
# #     img = cv2.imread(img_path)
# #     label_path = img_path.replace("images", "labels").replace(".jpg", ".txt")

# #     # Draw ground truth
# #     gt_img = draw_yolo_boxes(img_path, label_path, color=(0, 255, 0), label_type="GT")

# #     # Run tiled inference
# #     detections = run_tiled_inference(model, img)
# #     pred_img = draw_combined_predictions(img, detections, color=(0, 0, 255))

# #     # --- Combine views ---
# #     fig, axs = plt.subplots(1, 2, figsize=(14, 6))
# #     axs[0].imshow(cv2.cvtColor(gt_img, cv2.COLOR_BGR2RGB))
# #     axs[0].set_title("Ground Truth (Green Boxes)")
# #     axs[0].axis("off")

# #     axs[1].imshow(cv2.cvtColor(pred_img, cv2.COLOR_BGR2RGB))
# #     axs[1].set_title("Tiled Prediction (Red Boxes)")
# #     axs[1].axis("off")
# #     plt.savefig(f"./tiled_inference.png")
