# -*- coding: utf-8 -*-
"""YOLO11m_with_tiling_CBAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oldAUbryY5kFj25cusHiW3gAm3qC9c0t
"""


from ultralytics import YOLO
import os
import cv2
import random
import matplotlib.pyplot as plt
# 🔴 MUST COME FIRST
# ===== CBAM REGISTRATION (REQUIRED) =====
import ultralytics.nn.tasks as tasks
from custom_modules import CBAM

# 🔥 THIS is what parse_model() uses
tasks.CBAM = CBAM


from ultralytics import YOLO

# dataset path
dataset_path = "/home/vietpham/dataset/dataset"
image_dir = os.path.join(dataset_path, "train_tiled/images/")
label_dir = os.path.join(dataset_path, "train_tiled/labels")


# Get all image files
image_files = [f for f in os.listdir(image_dir) if f.endswith((".jpg", ".png", ".jpeg"))]
print(f"Found {len(image_files)} training images.")

class_names = [
    "tlr", "tly", "tlg", "tlra", "tlya", "tlga", "tsra", "tsya", "tsga",
    "trra", "trya", "trga", "tura", "tuya", "tuga", "tln", "tlr", "tly", "tlg",
    "tlra", "tlya", "tlga", "tsra", "tsya", "tsga", "trra", "trya", "trga",
    "tura", "tuya", "tuga", "tln",
    "117", "118", "119", "120", "121", "122", "123", "124", "125", "126",
    "127", "128", "129", "130", "131", "132", "133", "134", "135", "136",
    "137", "138", "139", "140", "141",
    "tnr", "tny", "tng", "tcr", "tcg", "tcn",
    "tllv", "tllvr", "tllvy", "tllvg", "tlrv", "tlrvr", "tlrvy", "tlrvg",
    "tlbv", "tclv", "tclvr", "tclvg", "tcrv", "tcrvr", "tcrvg", "tcbv"
]

# Random sample images
image_files = [f for f in os.listdir(image_dir) if f.endswith((".jpg", ".png"))]
sample_images = random.sample(image_files, min(1, len(image_files)))

def draw_yolo_labels(image_path, label_path):
    img = cv2.imread(image_path)
    if img is None: return None
    h, w = img.shape[:2]

    with open(label_path, "r") as f:
        for line in f:
            cls, x, y, bw, bh = map(float, line.split())
            cls = int(cls)
            x1, y1 = int((x - bw / 2) * w), int((y - bh / 2) * h)
            x2, y2 = int((x + bw / 2) * w), int((y + bh / 2) * h)
            color = (0, 255, 0)
            label = class_names[cls] if cls < len(class_names) else str(cls)
            cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
            cv2.putText(img, label, (x1, y1 - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(15, 10))
for i, name in enumerate(sample_images):
    img_path = os.path.join(image_dir, name)
    label_path = os.path.join(label_dir, os.path.splitext(name)[0] + ".txt")
    img_disp = draw_yolo_labels(img_path, label_path)
    if img_disp is not None:
        plt.subplot(1, len(sample_images), i + 1)
        plt.imshow(img_disp)
        plt.axis("off")
        plt.title(name)
plt.show()

yaml_path = os.path.join(dataset_path, "data_tiled.yaml")
with open(yaml_path, "w") as f:
    f.write(f"""
path: {dataset_path}
train: train_tiled/images
val: val_tiled/images
test: test_tiled/images

names:
""")
    for i, name in enumerate(class_names):
        f.write(f"  {i}: {name}\n")

print(open(yaml_path).read())

# Choose model size: yolov8n (nano), yolov8s (small), yolov8m (medium), yolov8l (large)
model = YOLO('runs/yolov8m_dataset2_adaptive_tiling_cbam6/weights/last.pt')  # start from pretrained COCO weights
# model = YOLO('/content/drive/MyDrive/Applied ML/Lab/runs/traffic_light_yolo_tiling2/weights/best.pt')
model.info()

import ultralytics
from ultralytics import YOLO

# ✅ Check Ultralytics version
print("Ultralytics package version:", ultralytics.__version__)

# ✅ Print model details to see what version/core it's using
print("Model type:", type(model))
print("Model info:", model.info())

# ✅ Print model name or architecture
try:
    print("Model YAML path:", model.model.yaml_file)
except Exception as e:
    print("Could not get YAML file:", e)

# Train model
model.train(
    data=yaml_path,
    epochs=600,             # increase if you have GPU time
    imgsz=640,             # image size (can change to 416 or 1280)
    batch=32,
    name='yolov8m_dataset2_adaptive_tiling_cbam',
    project='./runs',  # where to save results
    device=[1],# use GPU if available
    verbose=False,
    patience=300
)

# Evaluate on validation set
metrics = model.val('runs/yolo11m_dataset2_adaptive_tiling_cbam/weights/best.pt')
print(metrics)

# Visualize predictions
results = model.predict(source=f"{dataset_path}/test_tiled/images", conf=0.25, save=True)

# from IPython.display import Image, display
# display(Image(filename="/content/drive/MyDrive/Applied ML/Lab/runs/traffic_light_yolo/results.png", width=800))

print(metrics.results_dict)
